version: "3.8"

services:
  mongo_db:
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    ports:
      - "27015:27017"
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
#  app:
#    depends_on:
#      - mongo_db
#    build: .
#    restart: on-failure
#    env_file: ./.env
#    ports:
#      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
#    environment:
#      SPRING_APPLICATION_JSON: '{
#          "spring.data.mongodb.uri" : "mongodb://$MONGODB_USER:$MONGODB_PASSWORD@mongo_db:$MONGODB_DOCKER_PORT/$MONGODB_DATABASE?authSource=admin"
#        }'
#    volumes:
#      - .m2:/root/.m2
#    stdin_open: true
#    tty: true